apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac-clusterrole.yaml
  - rbac-clusterrolebinding.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - jaeger-backend.yaml
  - tracing-policy.yaml
