apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac-clusterrole.yaml
  - rbac-clusterrolebinding.yaml
  - gateway.yaml
  - jaeger-backend.yaml
  - tracing-policy.yaml
  - kubernetes-api-backend.yaml
  - kubernetes-ca-configmap.yaml
  - kubernetes-api-tls-policy.yaml
  - jwt-auth-policy.yaml
